### ISSUE TITLE
Akka.Persistence fails to save snapshot when data is bigger than 65,535 bytes

### ISSUE THREAD

**Issue by diequeeq** [akkadotnet/Akka.Persistence.MySql#8]
When snapshot data is bigger than 65,535 bytes, following error is observed in logs:
Failed to save snapshot, Error: MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'snapshot' at row 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)

**Comment by diequeeq** [comment]
This is fixed now in [this](https://github.com/akkadotnet/Akka.Persistence.MySql/pull/10) pull request.
